Matrices

Matrices is a two dimensional array where numbers, symbols or expressions are arranged into rows and columns. Using the concept of lists,
one can easily define a matrix in python.

We define two matrices A and B.

In [1]:
A = [[1,2,3],[4,5,6],[7,8,9]]
B = [[9,8,7],[6,5,4],[3,2,1]]
print(A)
print(B)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[9, 8, 7], [6, 5, 4], [3, 2, 1]]


In [2]:
A[0][0]

1

In [3]:
A[0].append(10)
print(A)

[[1, 2, 3, 10], [4, 5, 6], [7, 8, 9]]


The matrix A being defined as a list of lists, Python supports adding a single element to a row or column which falsifies
the condition for matrices.

thus we use numpy package

Working with matrices can be made easier in python using Numpy package

Numpy is a library consisting of multidimensional array objects and package of functions for processing those arrays.
NumPy stands for Numerical Python. The following operations can be performed using NumPy.

1. Mathematical and logical operations on arrays.
2. Fourier transforms and routines for shape manipulation.
3. Operations related to linear algebra.

We can import the NumPy package using one of the following syntax-

import numpy
import numpy as np(preffered)
from numpy import *

In [4]:
import numpy as np

Numpy provides the function array() and matrix() to define a matrix.

In [5]:
A1 = np.array([[1,2,3],[2,3,4],[3,4,5]])
A1

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [6]:
M1 = np.array([[1,2,3],[3,4,5],[5,6,7]])
M1

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [7]:
M1.shape

(3, 3)

In [8]:
M2 = np.array([[1,2,3],[2,3,4],[1,2,3],[1,2,3]])
print(M2.shape[0]) #No. of rows
print(M2.shape[1]) #No. of columns

4
3


The no. of elements is given by size function.

In [9]:
M1.size #No. of rows * No. of columns

9

The function zeros() and ones() create arrays with 0 or 1 of given shape.
By default it gives float values.

In [10]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones((4,4), dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

Matrix operations

In [12]:
D = np.matrix([[1,2,3],[3,4,5],[5,6,7]])
print("The matrix D\n", D)
E = np.matrix([[3,2,9],[3,8,1],[1,0,7]])
print("\nThe matrix E\n", E)
F = np.matrix([[11,2,3],[3,10,7],[5,8,2]])
print("\nThe matrix F\n", F)

The matrix D
 [[1 2 3]
 [3 4 5]
 [5 6 7]]

The matrix E
 [[3 2 9]
 [3 8 1]
 [1 0 7]]

The matrix F
 [[11  2  3]
 [ 3 10  7]
 [ 5  8  2]]


In [13]:
D+E

matrix([[ 4,  4, 12],
        [ 6, 12,  6],
        [ 6,  6, 14]])

In [14]:
np.add(D,E)

matrix([[ 4,  4, 12],
        [ 6, 12,  6],
        [ 6,  6, 14]])

In [15]:
D-E

matrix([[-2,  0, -6],
        [ 0, -4,  4],
        [ 4,  6,  0]])

In [16]:
np.subtract(D,E)

matrix([[-2,  0, -6],
        [ 0, -4,  4],
        [ 4,  6,  0]])

In [17]:
np.multiply(D,E) #Not matrix multiplication..its just element wise multiplication.

matrix([[ 3,  4, 27],
        [ 9, 32,  5],
        [ 5,  0, 49]])

In [18]:
#Matrix Multiplication
D*E

matrix([[ 12,  18,  32],
        [ 26,  38,  66],
        [ 40,  58, 100]])

In [19]:
D.dot(E)

matrix([[ 12,  18,  32],
        [ 26,  38,  66],
        [ 40,  58, 100]])

In [20]:
np.dot(D,E)

matrix([[ 12,  18,  32],
        [ 26,  38,  66],
        [ 40,  58, 100]])

In [21]:
E/D

matrix([[3. , 1. , 3. ],
        [1. , 2. , 0.2],
        [0.2, 0. , 1. ]])

In [22]:
np.divide(E,D)

matrix([[3. , 1. , 3. ],
        [1. , 2. , 0.2],
        [0.2, 0. , 1. ]])

In [23]:
#User Input matrix:

In [24]:
import numpy as np

row = int(input("Number of rows:"))
col = int(input("Number of columns:"))
print("Enter the entries in a single line (seperated by space):")
entries = list(map(int, input().split()))
matrix = np.array(entries).reshape(row,col)
print(matrix)

Number of rows: 3
Number of columns: 4


Enter the entries in a single line (seperated by space):


 1 2 3 4 5 6 7 8 9 10 11 12


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [25]:
#sum of elements of matrix

np.sum(matrix)

78

In [26]:
#product of elements of matrix

np.prod(M2)

5184

In [27]:
#min and max element in a matrix

print(np.min(matrix))
print(np.max(matrix))

1
12


In [28]:
M = np.diag([3,3,3])
M

array([[3, 0, 0],
       [0, 3, 0],
       [0, 0, 3]])

In [29]:
#slicing
submatrix = M[0:2, 0:2]
print(submatrix)

[[3 0]
 [0 3]]


In [30]:
specific_rows_cols = M[:, 0:2]
print(specific_rows_cols)

[[3 0]
 [0 3]
 [0 0]]
